import os
import time
import erpc
import CppHeaderParser

from erpcgen_files.py.uart_rpc import client


cppheader = CppHeaderParser.CppHeader("./erpcgen_files/src/erpc_crc16.h")


def hello():
    # Grab the correct crc from the autogenerated header file
    for define in cppheader.defines:
        if 'ERPC_GENERATED_CRC' in define:
            crc_value = int(define.split(' ')[1])


    #transport = erpc.transport.SerialTransport("/dev/ttyUSB0", 115200)

    transport = erpc.transport.SerialTransport("COM5", 115200)
    transport.crc_16 = crc_value

    clientManager = erpc.client.ClientManager(transport, erpc.basic_codec.BasicCodec)

    print("Trying to open client\n")
    myClient = client.TEST_UARTClient(clientManager)

    # print("Turning Green LED on?")
    # myClient.turnGreenLEDON()
    #
    # time.sleep(3)
    #
    # print("Turning Green LED off?")
    # myClient.turnGreenLEDOFF()

    myClient.setupSerialUnderTest()
    time.sleep(1)
    myClient.testStart_blockingTX()

    time.sleep(5)
    myClient.testEnd_blockingTX()

if __name__ == "__main__":
    hello()

