/*
 * Generated by erpcgen 1.6.0 on Fri Jun  1 15:06:24 2018.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "uart_rpc_server.h"
#include <new>
#include "erpc_port.h"

#if 10600 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_GENERATED_CRC) || ERPC_GENERATED_CRC != 46132
#error "Macro 'ERPC_GENERATED_CRC' should be defined with value 46132."
#endif


using namespace erpc;
#if !(__embedded_cplusplus)
using namespace std;
#endif

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif

// for mdk/keil do not forgett add "--muldefweak" for linker
extern const uint32_t erpc_generated_crc;
#pragma weak erpc_generated_crc
extern const uint32_t erpc_generated_crc = 46132;

// Call the correct server shim based on method unique ID.
erpc_status_t TEST_UART_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory)
{
    switch (methodId)
    {
        case kTEST_UART_turnGreenLEDON_id:
            return turnGreenLEDON_shim(codec, messageFactory, sequence);

        case kTEST_UART_turnGreenLEDOFF_id:
            return turnGreenLEDOFF_shim(codec, messageFactory, sequence);

        case kTEST_UART_setupSerialUnderTest_id:
            return setupSerialUnderTest_shim(codec, messageFactory, sequence);

        case kTEST_UART_testStart_blockingTX_id:
            return testStart_blockingTX_shim(codec, messageFactory, sequence);

        case kTEST_UART_testEnd_blockingTX_id:
            return testEnd_blockingTX_shim(codec, messageFactory, sequence);

        default:
            return kErpcStatus_InvalidArgument;
    }
}

// Server shim for turnGreenLEDON of TEST_UART interface.
erpc_status_t TEST_UART_service::turnGreenLEDON_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    // startReadMessage() was already called before this shim was invoked.


    // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = true;
#endif
    if (!err)
    {
        turnGreenLEDON();
    }
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = false;
#endif

    // preparing MessageBuffer for serializing data
    if (!err)
    {
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    // preparing codec for serializing data
    codec->reset();

    // Build response message.
    if (!err)
    {
        err = codec->startWriteMessage(kReplyMessage, kTEST_UART_service_id, kTEST_UART_turnGreenLEDON_id, sequence);
    }



    return err;
}

// Server shim for turnGreenLEDOFF of TEST_UART interface.
erpc_status_t TEST_UART_service::turnGreenLEDOFF_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    // startReadMessage() was already called before this shim was invoked.


    // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = true;
#endif
    if (!err)
    {
        turnGreenLEDOFF();
    }
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = false;
#endif

    // preparing MessageBuffer for serializing data
    if (!err)
    {
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    // preparing codec for serializing data
    codec->reset();

    // Build response message.
    if (!err)
    {
        err = codec->startWriteMessage(kReplyMessage, kTEST_UART_service_id, kTEST_UART_turnGreenLEDOFF_id, sequence);
    }



    return err;
}

// Server shim for setupSerialUnderTest of TEST_UART interface.
erpc_status_t TEST_UART_service::setupSerialUnderTest_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    // startReadMessage() was already called before this shim was invoked.


    // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = true;
#endif
    if (!err)
    {
        setupSerialUnderTest();
    }
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = false;
#endif

    // preparing MessageBuffer for serializing data
    if (!err)
    {
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    // preparing codec for serializing data
    codec->reset();

    // Build response message.
    if (!err)
    {
        err = codec->startWriteMessage(kReplyMessage, kTEST_UART_service_id, kTEST_UART_setupSerialUnderTest_id, sequence);
    }



    return err;
}

// Server shim for testStart_blockingTX of TEST_UART interface.
erpc_status_t TEST_UART_service::testStart_blockingTX_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    // startReadMessage() was already called before this shim was invoked.


    // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = true;
#endif
    if (!err)
    {
        testStart_blockingTX();
    }
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = false;
#endif

    // preparing MessageBuffer for serializing data
    if (!err)
    {
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    // preparing codec for serializing data
    codec->reset();

    // Build response message.
    if (!err)
    {
        err = codec->startWriteMessage(kReplyMessage, kTEST_UART_service_id, kTEST_UART_testStart_blockingTX_id, sequence);
    }



    return err;
}

// Server shim for testEnd_blockingTX of TEST_UART interface.
erpc_status_t TEST_UART_service::testEnd_blockingTX_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    // startReadMessage() was already called before this shim was invoked.


    // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = true;
#endif
    if (!err)
    {
        testEnd_blockingTX();
    }
#if ERPC_NESTED_CALLS_DETECTION
    nestingDetection = false;
#endif

    // preparing MessageBuffer for serializing data
    if (!err)
    {
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    // preparing codec for serializing data
    codec->reset();

    // Build response message.
    if (!err)
    {
        err = codec->startWriteMessage(kReplyMessage, kTEST_UART_service_id, kTEST_UART_testEnd_blockingTX_id, sequence);
    }



    return err;
}
erpc_service_t create_TEST_UART_service()
{
    return new (nothrow) TEST_UART_service();
}
