/*
 * Generated by erpcgen 1.6.0 on Fri Jun  1 15:06:24 2018.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_uart_rpc_server_h_)
#define _uart_rpc_server_h_

#ifdef __cplusplus
#include "server.h"
extern "C"
{
#include "uart_rpc.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10600 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_GENERATED_CRC) || ERPC_GENERATED_CRC != 46132
#error "Macro 'ERPC_GENERATED_CRC' should be defined with value 46132."
#endif



/*!
 * @brief Service subclass for TEST_UART.
 */
class TEST_UART_service : public erpc::Service
{
public:
    TEST_UART_service() : Service(kTEST_UART_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for turnGreenLEDON of TEST_UART interface. */
    erpc_status_t turnGreenLEDON_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for turnGreenLEDOFF of TEST_UART interface. */
    erpc_status_t turnGreenLEDOFF_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for setupSerialUnderTest of TEST_UART interface. */
    erpc_status_t setupSerialUnderTest_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for testStart_blockingTX of TEST_UART interface. */
    erpc_status_t testStart_blockingTX_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for testEnd_blockingTX of TEST_UART interface. */
    erpc_status_t testEnd_blockingTX_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "uart_rpc.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_TEST_UART_service(void);
#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _uart_rpc_server_h_
